<?xml version="1.0" ?>
<robot xmlns:xacro="http://wiki.ros.org/xacro">
  <xacro:include filename="$(find fanuc_resources)/urdf/common_materials.xacro"/>
  <xacro:macro name="lrmate200ic" params="prefix claw_base_length claw_hand_depth claw_finger_length ">


    <!-- Used for fixing robot to Gazebo 'base_link' -->
    <link name="world"/>
    <joint name="joint_world-base_link" type="fixed">
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <parent link="world"/>
      <child link="${prefix}base_link"/>
    </joint>



    <!-- links: main serial chain -->
    <link name="${prefix}base_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://lrmate200ic_support/meshes/lrmate200ic/visual/base_link.stl"/>
        </geometry>
        <xacro:material_fanuc_gray24 />
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://lrmate200ic_support/meshes/lrmate200ic/collision/base_link.stl"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="10"/>
        <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0"/>
      </inertial>
    </link>

    <link name="${prefix}link_1">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://lrmate200ic_support/meshes/lrmate200ic/visual/link_1.stl"/>
        </geometry>
        <xacro:material_fanuc_yellow />
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://lrmate200ic_support/meshes/lrmate200ic/collision/link_1.stl"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="8"/>
        <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0"/>
      </inertial>
    </link>

    <link name="${prefix}link_2">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://lrmate200ic_support/meshes/lrmate200ic/visual/link_2.stl"/>
        </geometry>
        <xacro:material_fanuc_yellow />
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://lrmate200ic_support/meshes/lrmate200ic/collision/link_2.stl"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="5"/>
        <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0"/>
      </inertial>
    </link>

    <link name="${prefix}link_3">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://lrmate200ic_support/meshes/lrmate200ic/visual/link_3.stl"/>
        </geometry>
        <xacro:material_fanuc_yellow />
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://lrmate200ic_support/meshes/lrmate200ic/collision/link_3.stl"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="3"/>
        <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0"/>
      </inertial>
    </link>

    <link name="${prefix}link_4">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://lrmate200ic_support/meshes/lrmate200ic/visual/link_4.stl"/>
        </geometry>
        <xacro:material_fanuc_yellow />
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://lrmate200ic_support/meshes/lrmate200ic/collision/link_4.stl"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="2"/>
        <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0"/>
      </inertial>
    </link>

    <link name="${prefix}link_5">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://lrmate200ic_support/meshes/lrmate200ic/visual/link_5.stl"/>
        </geometry>
        <xacro:material_fanuc_yellow />
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://lrmate200ic_support/meshes/lrmate200ic/collision/link_5.stl"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="1"/>
        <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0"/>
      </inertial>
    </link>

    <link name="${prefix}link_6">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://lrmate200ic_support/meshes/lrmate200ic/visual/link_6.stl"/>
        </geometry>
        <xacro:material_fanuc_black />
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://lrmate200ic_support/meshes/lrmate200ic/collision/link_6.stl"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="0.5"/>
        <inertia ixx="0.1" ixy="0.0" ixz="0.0" iyy="0.1" iyz="0.0" izz="0.1"/>
      </inertial>
    </link>

    <!-- joints: main serial chain -->
    <joint name="${prefix}joint_1" type="revolute">
      <origin xyz="0 0 0.330" rpy="0 0 0" />
      <parent link="${prefix}base_link" />
      <child link="${prefix}link_1" />
      <axis xyz="0 0 1" />
      <limit effort="0" lower="-2.9671" upper="2.9671" velocity="6.1087" />
      <dynamics damping="0.7"/>
    </joint>
    <joint name="${prefix}joint_2" type="revolute">
      <origin xyz="0.075 0 0" rpy="0 0 0" />
      <parent link="${prefix}link_1" />
      <child link="${prefix}link_2" />
      <axis xyz="0 1 0" />
      <limit effort="0" lower="-1.0472" upper="2.4435" velocity="6.1087" />
      <dynamics damping="0.7"/>
    </joint>
    <joint name="${prefix}joint_3" type="revolute">
      <origin xyz="0 0 0.300" rpy="0 0 0" />
      <parent link="${prefix}link_2" />
      <child link="${prefix}link_3" />
      <axis xyz="0 -1 0" />
      <limit effort="0" lower="-2.4784" upper="4.0143" velocity="6.9813" />
      <dynamics damping="0.7"/>
    </joint>
    <joint name="${prefix}joint_4" type="revolute">
      <origin xyz="0 0 0.075" rpy="0 0 0"/>
      <parent link="${prefix}link_3"/>
      <child link="${prefix}link_4"/>
      <axis xyz="-1 0 0"/>
      <limit effort="0" lower="-3.3161" upper="3.3161" velocity="7.8540" />
      <dynamics damping="0.7"/>
    </joint>
    <joint name="${prefix}joint_5" type="revolute">
      <origin xyz="0.320 0 0" rpy="0 0 0"/>
      <parent link="${prefix}link_4"/>
      <child link="${prefix}link_5"/>
      <axis xyz="0 -1 0"/>
      <limit effort="0" lower="-2.0944" upper="2.0944" velocity="7.8540" />
      <dynamics damping="0.7"/>
    </joint>
    <joint name="${prefix}joint_6" type="revolute">
      <origin xyz="0.080 0 0" rpy="0 0 0"/>
      <parent link="${prefix}link_5"/>
      <child link="${prefix}link_6"/>
      <axis xyz="-1 0 0"/>
      <limit effort="0" lower="-6.2832" upper="6.2832" velocity="12.5664" />
      <dynamics damping="0.7"/>
    </joint>

    <!-- ROS-Industrial 'base' frame: base_link to Fanuc World Coordinates transform -->
    <link name="${prefix}base" />

    <joint name="${prefix}base_link-base" type="fixed">
      <origin xyz="0 0 0.330" rpy="0 0 0"/>
      <parent link="${prefix}base_link"/>
      <child link="${prefix}base"/>
    </joint>

    <!-- ROS-Industrial 'flange' frame: attachment point for EEF models -->
    <!-- <link name="${prefix}flange" />

    <joint name="${prefix}joint_6-flange" type="fixed">
      <origin xyz="0 0 0" rpy="0 0 0" />
      <parent link="${prefix}link_6" />
      <child link="${prefix}flange" />
    </joint> -->

    <!-- ROS-Industrial 'tool0' frame: all-zeros tool frame -->
    <!-- link name="${prefix}tool0" />
    <joint name="${prefix}link_6-tool0" type="fixed">
      <origin xyz="0 0 0" rpy="${pi} ${-pi/2.0} 0" />
      <parent link="${prefix}link_6" />
      <child link="${prefix}tool0" />
    </joint> -->

    <!--The changes are as follows -->

    <!--claw_base is the EEF of Group manipulator. Its position and orientation is related to (joint) ${prefix}link_6-claw_base -->
    <joint name="${prefix}link_6-claw_base" type="fixed">
      <origin xyz="0 0 0" rpy="${pi} ${-pi/2.0} 0" />
      <parent link="${prefix}link_6" />
      <child link="${prefix}claw_base" />
    </joint>


    <!-- additional mechanical claw -->
    <link name="${prefix}claw_base">
      <visual>
        <origin xyz="0 0 ${claw_base_length/2.0}" rpy="0 0 0" />
        <geometry> 
          <cylinder length="${claw_base_length}" radius="0.01"/>
        </geometry>
        <material name="white">
          <color rgba="1.0 1.0 1.0 1.0"/> 
        </material>
      </visual>
      <collision> 
        <origin xyz="0 0 ${claw_base_length/2.0}" rpy="0 0 0" />
        <geometry> 
          <cylinder length="${claw_base_length}" radius="0.01"/>
        </geometry>      	
      </collision>
      <inertial>
        <origin xyz="0 0 ${claw_base_length/2.0}" rpy="0 0 0" />
        <mass value="0.1"/>
        <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01"/>
      </inertial>
    </link>

    <joint name="${prefix}claw_base-claw_hand" type="fixed">
      <origin xyz="0 0 ${claw_base_length}" rpy="0 0 0" />
      <parent link="${prefix}claw_base" />
      <child link="${prefix}claw_hand" />
    </joint>

    <link name="${prefix}claw_hand">
      <visual>
        <origin xyz="0 0 ${claw_hand_depth/2.0}" rpy="0 0 0" />
        <geometry> 
          <box size="${claw_hand_depth*2.5} ${claw_hand_depth*5.0} ${claw_hand_depth}"/>
        </geometry>
        <material name="black">
          <color rgba="0.0 0.0 0.0 1.0"/> 
        </material>
      </visual>
      <collision> 
        <origin xyz="0 0 ${claw_hand_depth/2.0}" rpy="0 0 0" />
        <geometry> 
          <box size="${claw_hand_depth*2.5} ${claw_hand_depth*5.0} ${claw_hand_depth}"/>
        </geometry>     	
      </collision>
      <inertial>
        <origin xyz="0 0 ${claw_hand_depth/2.0}" rpy="0 0 0" />
        <mass value="0.1"/>
        <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01"/>
      </inertial>
    </link>  

    <joint name="${prefix}joint_claw_finger1" type="prismatic">
      <origin xyz="0 ${claw_hand_depth*2.0} ${claw_hand_depth}" rpy="0 0 0" />
      <axis xyz="0 1 0" />
      <limit lower="-${claw_hand_depth*1.8}" upper="0" effort="10.0" velocity="1.0"/>
      <parent link="${prefix}claw_hand" />
      <child link="${prefix}claw_finger1" />
      <dynamics damping="0.7"/>
    </joint>
    
    <link name="${prefix}claw_finger1">
      <visual>
        <origin xyz="0 0 ${claw_finger_length/2.0}" rpy="0 0 0" />
        <geometry> 
          <box size="${claw_hand_depth*2.0} 0.01 ${claw_finger_length}"/>
        </geometry>
        <material name="white">
          <color rgba="1.0 1.0 1.0 1.0"/> 
        </material>
      </visual>
      <collision> 
        <origin xyz="0 0 ${claw_finger_length/2.0}" rpy="0 0 0" />
        <geometry> 
          <box size="${claw_finger_length/2.0} 0.01 ${claw_finger_length}" />
        </geometry>    	
      </collision>
      <inertial>
        <origin xyz="0 0 ${claw_finger_length/2.0}" rpy="0 0 0" />
        <mass value="0.1"/>
        <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01"/>
      </inertial>
    </link>  

    <joint name="${prefix}joint_claw_finger2" type="prismatic">
      <origin xyz="0 -${claw_hand_depth*2.0} ${claw_hand_depth}" rpy="0 0 0" />
      <axis xyz="0 1 0" />
      <limit lower="0" upper="${claw_hand_depth*1.8}" effort="10.0" velocity="1.0"/>
      <!--<mimic joint="${prefix}joint_claw_finger1" multiplier="-1" offset="0" />-->
      <parent link="${prefix}claw_hand" />
      <child link="${prefix}claw_finger2" />
      <dynamics damping="0.7"/>
    </joint>

    <link name="${prefix}claw_finger2">
      <visual>
        <origin xyz="0 0 ${claw_finger_length/2.0}" rpy="0 0 0" />
        <geometry> 
          <box size="${claw_hand_depth*2.0} 0.01 ${claw_finger_length}"/>
        </geometry>
        <material name="white">
          <color rgba="1.0 1.0 1.0 1.0"/> 
        </material>
      </visual>
      <collision> 
        <origin xyz="0 0 ${claw_finger_length/2.0}" rpy="0 0 0" />
        <geometry> 
          <box size="${claw_finger_length/2.0} 0.01 ${claw_finger_length}" />
        </geometry>    	
      </collision>
      <inertial>
        <origin xyz="0 0 ${claw_finger_length/2.0}" rpy="0 0 0" />
        <mass value="0.1"/>
        <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01"/>
      </inertial>
    </link>

    <joint name="${prefix}claw_hand-claw_end" type="fixed">
      <origin xyz="0 0 ${claw_hand_depth + claw_finger_length}" rpy="0 0 0" />
      <parent link="${prefix}claw_hand" />
      <child link="${prefix}claw_end" />
    </joint>

    <!--claw_end is the EEF of Group claw. Its position and orientation is related to (joint) ${prefix}claw_hand-claw_end -->
    <link name="${prefix}claw_end"/> 
    

  </xacro:macro>
</robot>
